runtime: nodejs20
service: backend
entrypoint: node src/app.js

handlers:
  - url: /api/.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
